// Self-discovering source-scan fitness guards for web invariants that the
// project's NIS2 / CLAUDE rules state but nothing else enforces. These walk
// the whole src/ tree (excluding tests and the generated paraglide output) and
// fail the build when a forbidden pattern reappears — the web equivalent of
// the Go archtest fitness functions.

import { describe, it, expect } from 'vitest';
import { readdirSync, readFileSync, statSync } from 'node:fs';
import { join, dirname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const srcRoot = join(dirname(fileURLToPath(import.meta.url)), '..'); // .../src

function walk(dir: string): string[] {
	const out: string[] = [];
	for (const entry of readdirSync(dir)) {
		// paraglide is generated by `npm run check`; never our source.
		if (entry === 'paraglide' || entry === 'node_modules') continue;
		const p = join(dir, entry);
		if (statSync(p).isDirectory()) {
			out.push(...walk(p));
		} else if (/\.(ts|svelte)$/.test(entry) && !/\.(test|spec)\.ts$/.test(entry)) {
			out.push(p);
		}
	}
	return out;
}

function scan(re: RegExp): string[] {
	const flags = 'g' + (re.flags.includes('s') ? 's' : '');
	const hits: string[] = [];
	for (const f of files) {
		const src = readFileSync(f, 'utf8');
		const g = new RegExp(re.source, flags);
		let m: RegExpExecArray | null;
		while ((m = g.exec(src)) !== null) {
			const line = src.slice(0, m.index).split('\n').length;
			hits.push(`${relative(srcRoot, f)}:${line}: ${m[0].replace(/\s+/g, ' ')}`);
		}
	}
	return hits;
}

const files = walk(srcRoot);

describe('web source invariants (NIS2 / CLAUDE)', () => {
	// matches-zero guard: if the walk returns nothing the scans below pass
	// vacuously, so assert the detector actually sees source.
	it('scans a non-empty set of source files', () => {
		expect(files.length).toBeGreaterThan(0);
	});

	// G5: "Every .catch() logs at minimum at debug level. .catch(() => {}) and
	// .catch(() => undefined) are findings." Silent error swallowing hides
	// real failures. The `s` flag lets the empty body span lines.
	it('G5: no silently-swallowing .catch(() => {}) / .catch(() => undefined)', () => {
		const hits = scan(/\.catch\(\s*(?:async\s*)?\(\s*\)\s*=>\s*(?:\{\s*\}|undefined)\s*\)/s);
		expect(
			hits,
			`empty .catch() swallows errors — log at >= debug instead:\n${hits.join('\n')}`
		).toEqual([]);
	});

	// G6: "IDs use ULID, never crypto.randomUUID()." Forbid randomUUID and the
	// uuid package so client-generated identifiers stay ULIDs.
	it('G6: no crypto.randomUUID() / uuid package — IDs are ULIDs', () => {
		const hits = scan(/\brandomUUID\s*\(|from\s+['"]uuid['"]|require\(\s*['"]uuid['"]\s*\)|\buuidv4\s*\(/);
		expect(hits, `use a ULID, not randomUUID/uuid:\n${hits.join('\n')}`).toEqual([]);
	});
});
